#!/bin/bash

if [ ! -d /home/teamcity/buildAgent ]; then
	mkdir -p /home/teamcity/buildAgent \
		&& cd /home/teamcity/buildAgent \
		&& wget $TEAMCITY_URL/update/buildAgent.zip \
		&& unzip buildAgent.zip && rm buildAgent.zip \
		&& cp conf/buildAgent{.dist,}.properties \
		&& sed -i 's#^\(serverUrl=\).*$#\1'$TEAMCITY_URL'#' conf/buildAgent.properties \
		&& sed -i 's#^\(name=\).*$#\1'$AGENT_NAME'#' conf/buildAgent.properties \
		&& chmod a+x /home/teamcity/buildAgent/bin/agent.sh
fi
exec /home/teamcity/buildAgent/bin/agent.sh run
